name: "Generate and publish"
on:
  [push]

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate and publish mappings
        run: ./gradlew publish --stacktrace
        env:
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
